#Imagen de origen:
FROM python:3.13.11-slim
#Para cargar UV:
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

#Instalacion de dependencias, si ya se tiene UV no se hace por pip, se salta
#este paso
#RUN pip install pandas pyarrow 

#Establecer directorio de trabajo
WORKDIR /app

#Copiar archivos de dependencias del proyecto
COPY pyproject.toml .python-version uv.lock ./

#Ejecutar comando para sincronizar dependencias con UV
RUN uv sync --locked 

#Copiar archivo o archivos necesarios para el proyecto, en el caso de que 
#el copy no tenga un argumento --from se copia desde el pc de trabajo:
COPY ingest_zones.py ./

#Para ejecutar directamente el codigo sin entrar a terminal
ENTRYPOINT ["uv", "run", "python", "ingest_zones.py"]